### ISSUE TITLE
non-standard use of data/ directory

### ISSUE THREAD

**Issue by lwaldron** [LiNk-NY/curatedTCGAManu#8]
Shouldn't these be in the `inst/data/` directory, to avoid warnings about non-standard use of the `data/` directory?

https://github.com/LiNk-NY/curatedTCGAManu/blob/38166bd3ed6c011c0ddb43def5fc6994c58059a4/vignettes/Figures3n4_GSEA_PanCan.Rmd#L305

More generally, the use of relative paths and lack of "vignettebuilder" in vignettes seems to imply that building should be done on individual vignettes and not as a package. Can you clarify building instructions in the README.md?

**Comment by LiNk-NY** [comment]
I've moved the datasets to the `inst/data` folder. 
I've updated the front matter for the vignettes. It looks any templates are ignored and only `rmarkdown::render` is used to build the pages for the `gh-pages` branch. 
I will clarify the instructions in the `README.md`

**Comment by LiNk-NY** [comment]
I've updated the `README.md` / home page on the website. I will expand on it more and add some directions for users to see the vignettes and re-organization of the vignette pages...
